name = "PuppyBook"
uuid = "5320df96-9774-11ea-008e-b50a9b22ffbe"
authors = ["Alessandro dalle Sasse"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
